//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publess.Data.Models
{
    using System;
    using System.Data.Entity;
    //using System.Data.Entity.Infrastructure;
    //using Microsoft.Data.Entity.Infrastructure;
    //using Microsoft.Data.Entity;

    using Publess.Core.Data;



    //using Microsoft.Extensions.Configuration;



    public partial class PublessEntities : DbContext, IPublessDbContext
    {
        //    //public PublessEntities()
        //    //    : base("name=PublessEntities")
        //    //{
        //    //}

        //    //public PublessEntities(IServiceProvider serviceProvider)
        //    //	: base(serviceProvider)
        //    //{

        //    //}

        //    public PublessEntities(IServiceProvider serviceProvider, DbContextOptions options)
        //        : base(serviceProvider, options)
        //    {
        //        //options.UseSqlServer(Startup.Configuration.Get("Data:DefaultConnection:ConnectionString"));
        //    }

        public PublessEntities(string nameOrConnectionString)
            :base(nameOrConnectionString:nameOrConnectionString)
        {

        }

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        IDbSet<TEntity> IDbContext.Set<TEntity>()
        {
            return base.Set<TEntity>();
        }


        //    //protected override void OnConfiguring(DbContextOptionsBuilder options)
        //    //{
        //    //    options.UseSqlServer(Startup.Configuration.Get("Data:DefaultConnection:ConnectionString"));
        //    //}

        public virtual IDbSet<Post> Posts { get; set; }
    }
}
