//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Publess.Data.Models
{
    using System;
    //using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Microsoft.Data.Entity.Infrastructure;
    using Microsoft.Data.Entity;

    using Publess.Core.Data;



    using Microsoft.Extensions.Configuration;



    public partial class PublessEntities : DbContext, IPublessDbContext
    {
        //public PublessEntities()
        //    : base("name=PublessEntities")
        //{
        //}

        //public PublessEntities(IServiceProvider serviceProvider)
        //	: base(serviceProvider)
        //{

        //}

        public PublessEntities(IServiceProvider serviceProvider, DbContextOptions options)
            : base(serviceProvider, options)
        {
            //options.UseSqlServer(Startup.Configuration.Get("Data:DefaultConnection:ConnectionString"));
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        System.Data.Entity.IDbSet<TEntity> IDbContext.Set<TEntity>()
        {
            throw new NotImplementedException();
        }


        //protected override void OnConfiguring(DbContextOptionsBuilder options)
        //{
        //    options.UseSqlServer(Startup.Configuration.Get("Data:DefaultConnection:ConnectionString"));
        //}

        public virtual System.Data.Entity.IDbSet<Post> Posts { get; set; }
    }
}
